accounts/urls.py
from django.urls import path
from .views import SignUpView
app_name = "accounts"

urlpatterns = [
    path("signup/",SignUpView.as_view(),name="signup")
]

pages/urls.py
from django.urls import path
from .views import HomeTempleView, ProductListView,ProductDetailView
app_name = "pages"


urlpatterns = [
    path("",HomeTempleView.as_view(),name='home'),
    path("men-shoes/",ProductListView.as_view(),name="products"),
    path("order-shoes/<str:pk>",ProductDetailView.as_view(),name="product")
]

shoeworld/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
    path("accounts/",include('accounts.urls')),
    path("",include('pages.urls'))
]

accounts/models.py
from django.db import models

# Create your models here.

pages/models.py
from django.db import models
import uuid
# Create your models here.
class Product(models.Model):
    CATEGORY = (
        ('sandels',"sandels"),
        ('sneakers','sneakers'),
        ('boots','boots'),
        ('formal shoe','formal shoe'),
        ('trainers','trainers'),
        ('slip-ons','slip-ons')
    )
    name = models.CharField(max_length=200)
    brand = models.CharField(max_length=200)
    category = models.CharField(max_length=11,choices=CATEGORY)
    price = models.PositiveIntegerField(default=0)
    quantity = models.PositiveIntegerField(default=0)
    id = models.UUIDField(default = uuid.uuid4,unique = True, primary_key = True, editable=False)

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.views import generic
from django.urls import  reverse_lazy

# Create your views here.

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = "accounts/signup.html"

pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,ListView,DetailView
from .models import Product

# Create your views here.

class HomeTempleView(TemplateView):
    template_name = 'pages/index.html'

class ProductListView(ListView):
    model = Product
    context_object_name = 'products'
    template_name = 'pages/men_shoe.html'

class ProductDetailView(DetailView):
    model = Product
    context_object_name = 'product'
    template_name = 'pages/order_shoe.html'

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
    <div>
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="login">
        </form>
    </div>
{% endblock content %}

pages/templates/pages/index.html
{% extends "base.html" %}

{% block content %}
<h1>home</h1>
<p><a href="{% url  'pages:products' %}">men</a></p>
{% endblock content %}

pages/templates/pages/men_shoe.html
{% extends "base.html" %}

{% block content %}
<h1>men shoe</h1>
    {% for product in products %}
    <div>
        <a href="{% url 'pages:product' product.id %}">
            <p>{{product.brand}}</p>
            <p>{{product.name}}</p>
        </a>
        <small>R {{product.price}}.00</small>
    </div>
    {% endfor %}
{% endblock content %}

pages/templates/pages/order_shoe.html
{% extends 'base.html' %}

{% block content %}
<div>
    
        <p>{{product.brand}}</p>
        <p>{{product.name}}</p>

    <small>R {{product.price}}.00</small>
</div>
    <button>order</button>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shoe World</title>
</head>
<body>
    {% include 'header.html' %}

    {% block content %}

    {% endblock content %}
    
    {% include 'footer.html' %}
</body>
</html>

templates/footer.html
<h3>this is the footer</h3>

templates/header.html
<header style="display: flex; justify-content: space-around; align-items: center;">
    <h1><a href="{% url 'pages:home'%}">Log</a></h1>
    <nav>
        <a href="{% url 'login' %}">login</a>
        <a href="{% url 'accounts:signup' %}">signup</a>
    </nav>
</header>